// ignore_for_file: constant_identifier_names

enum BannerType{
  FIRST_TIME_MOBILE_RECHARGE,
  MOBILE_RECHARGE,
  MEGA_OFFER,
  ADD_ADDRESS,
  PENDING_PAYMENT,
  TRACK_ORDER_BEFORE_SHIPMENT,
  TRACK_ORDER_AFTER_SHIPMENT,
  STATIC_BANNER,
  ORDER_REVIEW,
  MULTIPLE_BANNER
}